lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_2/lab_2/lab_2/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list, data_friend_list, details_friend

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add-friend/$', add_friend, name='add-friend'),
	url(r'^validate-npm/$', validate_npm, name='validate-npm'),
	url(r'^get-friend-list/delete1/(?P<friend_id>[0-9]+)/$', delete_friend, name='delete-friend'),
	url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
	url(r'^get-friend-list/details/(?P<friend_id>[0-9]+)/$', details_friend, name='details'),
    url(r'^data-friend-list/$', data_friend_list, name='data-friend-list'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
from lab_1.views import index as index_lab1
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
from django.views.generic.base import RedirectView
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
	url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
	url(r'^lab-3/', include(lab_3, namespace='lab-3')),
	url(r'^$', RedirectView.as_view(url='lab-4/', permanent=True),name='$'),
	url(r'^lab-4/', include(lab_4, namespace='lab-4')),
	url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
]

lab_7/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
        friend_name = models.CharField(max_length=400)
        npm = models.CharField(max_length=250)
        alamat = models.CharField(max_length=400, default="-")
        ttl = models.CharField(max_length=400, default="-")
        prodi = models.CharField(max_length=100, default="-")
        added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json
import requests

response = {}
csui_helper = CSUIhelper()

def index(request):
    # Page halaman menampilkan list mahasiswa yang ada
    # TODO berikan akses token dari backend dengan menggunakaan helper yang ada

    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
    friend_list = Friend.objects.all()
    page = request.GET.get('page')
    mahasiswa = paginate(page, mahasiswa_list)
    response = {"mahasiswa_list": mahasiswa, "friend_list": friend_list}
    html = 'lab_7/lab_7.html'
    return render(request, html, response)

def paginate(page, listData):
    paginator = Paginator(listData, 10)
    try:
        mahasiswa = paginator.page(page)
    except PageNotAnInteger:
        mahasiswa = paginator.page(1)
    except EmptyPage:
        mahasiswa = paginator.page(paginator.num_pages)
    return mahasiswa

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list.order_by('npm')
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

def data_friend_list(request):
    if request.method == 'GET':
        friend_list = Friend.objects.all()
        data = serializers.serialize("json", friend_list)
        return HttpResponse(data)

@csrf_exempt
def add_friend(request):
    boolean = len(Friend.objects.filter(npm=request.POST['npm'])) > 0
    if boolean:
        return JsonResponse({"boolean": True});
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        try:
            alamat = request.POST['alamat']
            ttl = request.POST['ttl']
            prodi = request.POST['prodi']
            friend = Friend(friend_name=name, npm=npm, alamat=alamat, ttl=ttl, prodi=prodi)
        except Exception as e:
            friend = Friend(friend_name=name, npm=npm)

        friend.save()
        data = model_to_dict(friend)
        return HttpResponse(data)

def delete_friend(request, friend_id):
    Friend.objects.filter(id=friend_id).delete()
    return HttpResponseRedirect('/lab-7/get-friend-list')

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    boolean = len(Friend.objects.filter(npm=npm)) > 0
    data = {
        'is_taken': boolean
    }
    return JsonResponse(data)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

def details_friend(request, friend_id):
    friend = Friend.objects.get(pk = friend_id)
    response['nama'] = friend.friend_name
    response['npm'] = friend.npm
    response['alamat'] = friend.alamat
    response['ttl'] = friend.ttl
    response['prodi'] = friend.prodi
    html = 'lab_7/details.html'
    return render(request, html, response)

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> Friend Fasilkom</h2>
                    <div id="friend-list" class="list-group">

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        $( document ).ready(function () {
            {# lengkapi pemanggilan ajax berikut untuk mengambil daftar teman yang ada di database #}
            $.ajax({
                method: "GET",
                url: '{% url "lab-7:data-friend-list" %}',
                success: function (data) {
                  if (JSON.parse(data).length > 0) {
                    $.each(JSON.parse(data), function(index, value){
                      console.log(value.pk);
                      console.log(value);
                      var deleteButton = "<button type='button' class= 'btn pull-right "
                      + "btn-danger btn-xs' onClick='delete1("+value.pk+")'>&times</button>";
                      var detailButton = "<button type='button' class= 'btn pull-right "
                      + "btn-primary btn-xs' onClick='detail1("+value.pk+")' style='margin-right:"
                      + " 15px;'>DETAILS</button>";
                      var html = "<a class='list-group-item clearfix' id='person"+value.pk+"'>"
                      + value.fields.friend_name + deleteButton + detailButton + "</a>";

                      $("div#friend-list").append(html);
                    });
                  }else { 
                    var html = "<div class='alert alert-danger text-center'>"
                    + "Tidak ada teman</div>";
                        $("#friend-list").append(html);
                  }
                },error: function(error){
                    alert("error");
                }
            });
        });
        var delete1 = function(pk){
          console.log(pk);
          window.open("delete1/"+pk+"/", '_self');
        }
        var detail1 = function(pk){
          console.log(pk);
          window.open("details/"+pk+"/", '_self');
        }
    </script>
{% endblock %}

lab_7/templates/lab_7/details.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-description" id="friend-description">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2 style="margin-bottom: 20px;">{{nama}}</h2>
                </div>
            </div>
            <div class="row">
              <div class="col-md-2 col-lg-2">
                  <h4>NPM</h4>
              </div>
              <div class="col-md-4 col-lg-4">
                  <h4>{{npm}}</h4>
              </div>
            </div>
            <div class="row">
              <div class="col-md-2 col-lg-2">
                  <h4>Prodi</h4>
              </div>
              <div class="col-md-4 col-lg-4">
                  <h4>{{prodi}}</h4>
              </div>
            </div>
            <div class="row">
              <div class="col-md-2 col-lg-2">
                  <h4>TTL</h4>
              </div>
              <div class="col-md-4 col-lg-4">
                  <h4>{{ttl}}</h4>
              </div>
            </div>
            <div class="row">
              <div class="col-md-2 col-lg-2">
                  <h4>Alamat</h4>
              </div>
              <div class="col-md-4 col-lg-4">
                  <h4 id="alamat">{{alamat}}</h4>
              </div>
            </div>
            <div class="row">
              <div id="googleMap" style="width:300px; height:200px; margin: 50px 0"></div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
<script>
	console.log($("#alamat").text());
	var address = $("#alamat").text();

	function initMap() {
		var geocoder = new google.maps.Geocoder();
		geocoder.geocode({'address': address}, function(results, status) {
      console.log(status);
			if (status === google.maps.GeocoderStatus.OK) {
				var propertiPeta = {
					center: results[0].geometry.location,
					zoom: 15,
					mapTypeId: google.maps.MapTypeId.ROADMAP
				};
				var peta = new google.maps.Map(document.getElementById("googleMap"), propertiPeta);
				var marker = new google.maps.Marker({
				  map: peta,
				  position: results[0].geometry.location
				});
			} else {
				var html = '<div class="alert alert-danger text-center">\
                            	Lokasi tidak ditemukan!\
                            </div>';
                $("#googleMap").append(html)
			}
		});
	}
</script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}', '{{ mahasiswa.alamat_mhs }}', '{{ mahasiswa.kota_lahir }}, {{ mahasiswa.tgl_lahir }}', '{{ mahasiswa.program.0.nm_org }} ({{ mahasiswa.program.0.nm_prg }})')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
                <ul class="pagination">
                    {% if mahasiswa_list.has_previous %}
                        <li><a href="{% url 'lab-7:index' %}">&laquo;</a></li>
                        <li><a href="?page={{ mahasiswa_list.previous_page_number }}">Previous</a></li>
                    {% else %}
                        <li class="disabled"><span>Previous</span></li>
                    {% endif %}
                    {% for i in mahasiswa_list.paginator.page_range %}
                        {% if mahasiswa_list.number == i %}
                          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                          <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if mahasiswa_list.has_next %}
                        <li><a href="?page={{ mahasiswa_list.next_page_number }}">Next</a></li>
                        <li><a href="?page={{ mahasiswa_list.paginator.num_pages }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>Next</span></li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">NPM</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name" style="margin-top: 10px;">NAME</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit" style="margin-top: 10px; margin-bottom: 10px;" class="btn-primary">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    var addFriend = function(nama, npm, alamat, ttl, prodi) {
        $.ajax({
            method: "POST",
            url: "{% url "lab-7:add-friend" %}",
            data: { name: nama, npm: npm, alamat: alamat, ttl: ttl, prodi: prodi},
            success : function (friend) {
                console.log(friend.boolean);
                if (friend.boolean) {
                    alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
                } else {
                  html = '<a class="list-group-item clearfix">' +
                      nama + " (" + npm + ")" +
                      '</a>';

                  $("#friend-list").append(html)
                  $("div.alert").hide()
                }
            },
        });
    };

    $("#add-friend").on("submit", function () {
       name = $("#field_name").val()
       npm = $("#field_npm").val()
        addFriend(name, npm)
        $("#field_name").val("")
        $("#field_npm").val("")
        event.preventDefault();
    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                console.log(data.is_taken);
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}